AppsLab-KE/backend-everyshilling

docs/everyshilling.yaml
- Added metadata content for the OpenAPI document
=> OpenAPI file

docs/everyshilling.yaml
- Implemented register endpoint for OpenAPI document
=> Register Endpoint

.gitignore, docs/everyshilling.yaml
- Verify OTP
- Update Password
=> Password reset endpoints

docs/everyshilling.yaml
- updated OpenAPI structure file (tags position)
=> OpenAPI doc

services/app-exchange/Dockerfile, services/app-otp/Dockerfile
Added Python and go Dockerfiles for the microservices
=> adding dockerfile for each microservice

services/app-authentication/cmd/root.go, services/app-authentication/cmd/server.go, services/app-authentication/internal/model/user.go
- Added project structure for App-authentication micro service
=> Project structure

services/app-otp/otp.mmd
- Added OTP sequence diagram to app-otp directory
=> Tw-76/ OTP sequence diagram

services/app-authentication/internal/routes/http/router.go
- Added the project structure from the login OTP endpoint in reference to the Open API Specification
=> Project Structure (login otp) WIP

docker-compose-dev.yml, docs/instructions.md
Setting up Postgres using docker container
=> Postgres DB setup

.gitpod.yml
Adding installation commands to gitpod file
=> Gitpod file

services/app-auth/internal/core/usecase/auth.go, services/app-auth/internal/routes/handlers/handler_wrapper.go
- Implemented reset password handler
=> Reset password Handler-WIP

services/app-auth/internal/core/usecase/auth.go, services/app-auth/internal/routes/handlers/handler_wrapper.go
- Applied  changes (in progress) for the login endpoint.
- All in the respective files under the App-Auth micro-service diectory.
=> WIP (Active Dev. phase)

services/app-auth/internal/core/usecase/auth.go, services/app-auth/internal/routes/handlers/reset.go
=> Reset endpoint

services/app-auth/internal/core/adapters/auth.go, services/app-auth/internal/errors/error.go, services/app-auth/internal/routes/handlers/signup.go
- Debugged Signup.go
- Customized error package
=> debugged signup handler

services/app-db/docs/liquibase/example-changelog.sql, services/app-db/docs/liquibase/liquibase.advanced.flowfile.yaml, services/app-db/docs/liquibase/liquibase.endstage.flow, services/app-db/docs/liquibase/liquibase.flowfile.yaml, services/app-db/docs/liquibase/liquibase.flowvariables.yaml, services/app-db/docs/liquibase/liquibase.properties
- Initialized Liquibase project
- Added User and OTP schema in the change log file
=> Liquibase Implementation

services/app-auth/internal/core/adapters/repo.go, services/app-auth/internal/core/service/session.go
- Implemented Invalidate method
=> Session Service

everyshilling_openapi.yaml
- Added Logout End point
- Added Refresh token endpoint
=> Logout and Refresh Token Endpoint

docs/everyshilling_openapi.yaml, services/app-auth/internal/core/adapters/service.go, services/app-auth/internal/core/adapters/usecase.go, services/app-auth/internal/core/service/auth.go, services/app-auth/internal/core/usecase/auth.go, services/app-auth/internal/dto/general_dto.go, services/app-auth/internal/dto/signup.go, services/app-auth/internal/routes/handlers/account-verification.go, services/app-auth/internal/routes/handlers/handler.gen.go
According to the review on Friday, JWT should only be generated after account verification
=> deauthenticate account verification

services/app-otp/otp/server.py
=> otp verification

docs/everyshilling_openapi.yaml
- Updated the data fields for Login, Register, and User endpoints
=> OpenAPI documentation file Update - WIP

services/app-auth/internal/core/service/auth.go, services/app-auth/internal/routes/handlers/handler.go
Canceling RPCs when they take too long
=> context with timeout

docs/everyshilling_openapi.yaml
- Updated the OpenAPI documentation for the remaining endpoints
=> Open API documentation

requirements.txt, services/app-otp/otp/cache.py, services/app-otp/otp/tests_cache.py
- Fixed bugs and updated tests 
- updated requirements.txt file
=> Updated Unittests 

Monitoring/docker-compose.yml, Monitoring/grafana.ini, Monitoring/prometheus.yml
adding grafana and prometheus monitoring tools using docker compose
The goal is to visualize the different services.
=> Setting up Monitoring for the dev environment
